/* automatically generated by rust-bindgen 0.72.1 */

#[repr(C)]
#[derive(Default)]
pub struct __IncompleteArrayField<T>(::core::marker::PhantomData<T>, [T; 0]);
impl<T> __IncompleteArrayField<T> {
    #[inline]
    pub const fn new() -> Self {
        __IncompleteArrayField(::core::marker::PhantomData, [])
    }
    #[inline]
    pub fn as_ptr(&self) -> *const T {
        self as *const _ as *const T
    }
    #[inline]
    pub fn as_mut_ptr(&mut self) -> *mut T {
        self as *mut _ as *mut T
    }
    #[inline]
    pub unsafe fn as_slice(&self, len: usize) -> &[T] {
        unsafe { ::core::slice::from_raw_parts(self.as_ptr(), len) }
    }
    #[inline]
    pub unsafe fn as_mut_slice(&mut self, len: usize) -> &mut [T] {
        unsafe { ::core::slice::from_raw_parts_mut(self.as_mut_ptr(), len) }
    }
}
impl<T> ::core::fmt::Debug for __IncompleteArrayField<T> {
    fn fmt(&self, fmt: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        fmt.write_str("__IncompleteArrayField")
    }
}
pub const TRACE_STRING_MAX_SIZE: u32 = 512;
pub const TRACE_MAGIC_HEADER: u32 = 1985229328;
pub const TRACE_VERSION_MAJOR: u32 = 0;
pub const TRACE_VERSION_MINOR: u32 = 6;
pub const TRACE_VERSION_PATCH: u32 = 0;
pub const TRACE_DEV_CONTEXT_GPRS: u32 = 31;
#[doc = " \\typedef trace_buffer_type_e\n\\brief Trace buffer type either MM, CM, SP etc."]
pub type trace_buffer_type_e = u8;
pub mod trace_buffer_type {
    #[doc = " \\enum trace_buffer_type\n\\brief Trace buffer type either MM, CM, or SP etc."]
    pub type Type = ::core::ffi::c_uint;
    pub const TRACE_MM_BUFFER: Type = 0;
    pub const TRACE_CM_BUFFER: Type = 1;
    pub const TRACE_SP_BUFFER: Type = 2;
    pub const TRACE_CM_UMODE_BUFFER: Type = 3;
    pub const TRACE_SP_STATS_BUFFER: Type = 4;
    pub const TRACE_MM_STATS_BUFFER: Type = 5;
}
#[doc = " \\typedef trace_header_type_e\n\\brief Trace buffer type either trace_buffer_std_header_t or trace_buffer_size_header_t."]
pub type trace_header_type_e = u8;
pub mod trace_header_type {
    #[doc = " \\enum trace_header_type\n\\brief Trace buffer header type."]
    pub type Type = ::core::ffi::c_uint;
    #[doc = "< Standard trace buffer header of type struct trace_buffer_std_header_t"]
    pub const TRACE_STD_HEADER: Type = 0;
    #[doc = "< Size only trace buffer header of type struct trace_buffer_size_header_t"]
    pub const TRACE_SIZE_HEADER: Type = 1;
}
#[doc = " \\typedef trace_type_e\n\\brief Trace packet type."]
pub type trace_type_e = u16;
pub mod trace_type {
    #[doc = " \\enum trace_type\n\\brief Trace packet types."]
    pub type Type = ::core::ffi::c_uint;
    pub const TRACE_TYPE_START: Type = 0;
    pub const TRACE_TYPE_STRING: Type = 0;
    pub const TRACE_TYPE_PMC_COUNTER: Type = 1;
    pub const TRACE_TYPE_PMC_COUNTERS_COMPUTE: Type = 2;
    pub const TRACE_TYPE_PMC_COUNTERS_MEMORY: Type = 3;
    pub const TRACE_TYPE_PMC_COUNTERS_SC: Type = 4;
    pub const TRACE_TYPE_PMC_COUNTERS_MS: Type = 5;
    pub const TRACE_TYPE_VALUE_U64: Type = 6;
    pub const TRACE_TYPE_VALUE_U32: Type = 7;
    pub const TRACE_TYPE_VALUE_U16: Type = 8;
    pub const TRACE_TYPE_VALUE_U8: Type = 9;
    pub const TRACE_TYPE_VALUE_FLOAT: Type = 10;
    pub const TRACE_TYPE_MEMORY: Type = 11;
    pub const TRACE_TYPE_EXCEPTION: Type = 12;
    pub const TRACE_TYPE_CMD_STATUS: Type = 13;
    pub const TRACE_TYPE_POWER_STATUS: Type = 14;
    pub const TRACE_TYPE_CUSTOM_EVENT: Type = 15;
    pub const TRACE_TYPE_USER_PROFILE_EVENT: Type = 16;
    pub const TRACE_TYPE_END: Type = 17;
}
pub mod trace_custom_type_sp {
    #[doc = " \\enum trace_custom_type_sp\n\\brief Trace custom type IDs for SP."]
    pub type Type = ::core::ffi::c_uint;
    pub const TRACE_CUSTOM_TYPE_SP_START: Type = 0;
    pub const TRACE_CUSTOM_TYPE_SP_PERF_GLOBALS: Type = 1;
    pub const TRACE_CUSTOM_TYPE_SP_POWER_GLOBALS: Type = 2;
    pub const TRACE_CUSTOM_TYPE_SP_POWER_STATES_GLOBALS: Type = 3;
    pub const TRACE_CUSTOM_TYPE_SP_OP_STATS: Type = 4;
    pub const TRACE_CUSTOM_TYPE_SP_COUNT: Type = 5;
    pub const TRACE_CUSTOM_TYPE_SP_END: Type = 999;
}
pub mod trace_custom_type_mm {
    #[doc = " \\enum trace_custom_type_mm\n\\brief Trace custom type IDs for MM."]
    pub type Type = ::core::ffi::c_uint;
    pub const TRACE_CUSTOM_TYPE_MM_START: Type = 1000;
    pub const TRACE_CUSTOM_TYPE_MM_COMPUTE_RESOURCES: Type = 1001;
    pub const TRACE_CUSTOM_TYPE_MM_COUNT: Type = 1002;
    pub const TRACE_CUSTOM_TYPE_MM_END: Type = 1999;
}
pub mod trace_custom_type_cm {
    #[doc = " \\enum trace_custom_type_cm\n\\brief Trace custom type IDs for CM."]
    pub type Type = ::core::ffi::c_uint;
    pub const TRACE_CUSTOM_TYPE_CM_START: Type = 2000;
    pub const TRACE_CUSTOM_TYPE_CM_COUNT: Type = 2001;
    pub const TRACE_CUSTOM_TYPE_CM_END: Type = 2999;
}
#[doc = " \\typedef trace_cmd_status_e\n\\brief Trace command statuses. Refers to enum trace_cmd_status."]
pub type trace_cmd_status_e = u8;
pub mod trace_cmd_status {
    #[doc = " \\enum trace_cmd_status\n\\brief Trace command statuses."]
    pub type Type = ::core::ffi::c_uint;
    #[doc = "< Conditional: Command is awaiting for Barrier to be released"]
    pub const CMD_STATUS_WAIT_BARRIER: Type = 1;
    #[doc = "< Command is popped/received from submission Queue."]
    pub const CMD_STATUS_RECEIVED: Type = 2;
    #[doc = "< Command is submitted for execution to respective component of device."]
    pub const CMD_STATUS_EXECUTING: Type = 3;
    #[doc = "< Command completed with a failure."]
    pub const CMD_STATUS_FAILED: Type = 4;
    #[doc = "< Command is aborted."]
    pub const CMD_STATUS_ABORTED: Type = 5;
    #[doc = "< Command completed successfully."]
    pub const CMD_STATUS_SUCCEEDED: Type = 6;
}
#[doc = " \\typedef pmc_counter_e\n\\brief Counter type of log timestamp. Refers to enum pmc_counter."]
pub type pmc_counter_e = u8;
pub mod pmc_counter {
    #[doc = " \\enum pmc_counter\n\\brief PMC counters to sample and log in trace."]
    pub type Type = ::core::ffi::c_uint;
    pub const PMC_COUNTER_HPMCOUNTER3: Type = 0;
    pub const PMC_COUNTER_HPMCOUNTER4: Type = 1;
    pub const PMC_COUNTER_HPMCOUNTER5: Type = 2;
    pub const PMC_COUNTER_HPMCOUNTER6: Type = 3;
    pub const PMC_COUNTER_HPMCOUNTER7: Type = 4;
    pub const PMC_COUNTER_HPMCOUNTER8: Type = 5;
    pub const PMC_COUNTER_SHIRE_CACHE_CYCLE: Type = 6;
    pub const PMC_COUNTER_SHIRE_CACHE_1: Type = 7;
    pub const PMC_COUNTER_SHIRE_CACHE_2: Type = 8;
    pub const PMC_COUNTER_MEMSHIRE_CYCLE: Type = 9;
    pub const PMC_COUNTER_MEMSHIRE_1: Type = 10;
    pub const PMC_COUNTER_MEMSHIRE_2: Type = 11;
    pub const PMC_COUNTER_MEMSHIRE0_CYCLE: Type = 12;
    pub const PMC_COUNTER_MEMSHIRE1_CYCLE: Type = 13;
    pub const PMC_COUNTER_MEMSHIRE2_CYCLE: Type = 14;
    pub const PMC_COUNTER_MEMSHIRE3_CYCLE: Type = 15;
    pub const PMC_COUNTER_MEMSHIRE4_CYCLE: Type = 16;
    pub const PMC_COUNTER_MEMSHIRE5_CYCLE: Type = 17;
    pub const PMC_COUNTER_MEMSHIRE6_CYCLE: Type = 18;
    pub const PMC_COUNTER_MEMSHIRE7_CYCLE: Type = 19;
    pub const PMC_COUNTER_MEMSHIRE0_1: Type = 20;
    pub const PMC_COUNTER_MEMSHIRE1_1: Type = 21;
    pub const PMC_COUNTER_MEMSHIRE2_1: Type = 22;
    pub const PMC_COUNTER_MEMSHIRE3_1: Type = 23;
    pub const PMC_COUNTER_MEMSHIRE4_1: Type = 24;
    pub const PMC_COUNTER_MEMSHIRE5_1: Type = 25;
    pub const PMC_COUNTER_MEMSHIRE6_1: Type = 26;
    pub const PMC_COUNTER_MEMSHIRE7_1: Type = 27;
    pub const PMC_COUNTER_MEMSHIRE0_2: Type = 28;
    pub const PMC_COUNTER_MEMSHIRE1_2: Type = 29;
    pub const PMC_COUNTER_MEMSHIRE2_2: Type = 30;
    pub const PMC_COUNTER_MEMSHIRE3_2: Type = 31;
    pub const PMC_COUNTER_MEMSHIRE4_2: Type = 32;
    pub const PMC_COUNTER_MEMSHIRE5_2: Type = 33;
    pub const PMC_COUNTER_MEMSHIRE6_2: Type = 34;
    pub const PMC_COUNTER_MEMSHIRE7_2: Type = 35;
}
#[repr(C, packed)]
#[derive(Debug, Default, Copy, Clone)]
pub struct trace_version_t {
    pub major: u16,
    pub minor: u16,
    pub patch: u16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of trace_version_t"][::core::mem::size_of::<trace_version_t>() - 6usize];
    ["Alignment of trace_version_t"][::core::mem::align_of::<trace_version_t>() - 1usize];
    ["Offset of field: trace_version_t::major"]
        [::core::mem::offset_of!(trace_version_t, major) - 0usize];
    ["Offset of field: trace_version_t::minor"]
        [::core::mem::offset_of!(trace_version_t, minor) - 2usize];
    ["Offset of field: trace_version_t::patch"]
        [::core::mem::offset_of!(trace_version_t, patch) - 4usize];
};
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct trace_init_info_t {
    #[doc = "< Base address for Trace buffer."]
    pub buffer: u64,
    #[doc = "< Total size of the Trace buffer."]
    pub buffer_size: u32,
    #[doc = "< Threshold for free memory in the buffer for each hart."]
    pub threshold: u32,
    #[doc = "< Bit Mask of Shire to enable Trace Capture."]
    pub shire_mask: u64,
    #[doc = "< Bit Mask of Thread within a Shire to enable Trace Capture."]
    pub thread_mask: u64,
    #[doc = "< This is a bit mask, each bit corresponds to a specific Event to trace."]
    pub event_mask: u32,
    #[doc = "< This is a bit mask representing a list of filters for a given event to trace."]
    pub filter_mask: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of trace_init_info_t"][::core::mem::size_of::<trace_init_info_t>() - 40usize];
    ["Alignment of trace_init_info_t"][::core::mem::align_of::<trace_init_info_t>() - 8usize];
    ["Offset of field: trace_init_info_t::buffer"]
        [::core::mem::offset_of!(trace_init_info_t, buffer) - 0usize];
    ["Offset of field: trace_init_info_t::buffer_size"]
        [::core::mem::offset_of!(trace_init_info_t, buffer_size) - 8usize];
    ["Offset of field: trace_init_info_t::threshold"]
        [::core::mem::offset_of!(trace_init_info_t, threshold) - 12usize];
    ["Offset of field: trace_init_info_t::shire_mask"]
        [::core::mem::offset_of!(trace_init_info_t, shire_mask) - 16usize];
    ["Offset of field: trace_init_info_t::thread_mask"]
        [::core::mem::offset_of!(trace_init_info_t, thread_mask) - 24usize];
    ["Offset of field: trace_init_info_t::event_mask"]
        [::core::mem::offset_of!(trace_init_info_t, event_mask) - 32usize];
    ["Offset of field: trace_init_info_t::filter_mask"]
        [::core::mem::offset_of!(trace_init_info_t, filter_mask) - 36usize];
};
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct trace_config_info_t {
    #[doc = "< This is a bit mask, each bit corresponds to a specific Event to trace."]
    pub event_mask: u32,
    #[doc = "< This is a bit mask representing a list of filters for a given event to trace."]
    pub filter_mask: u32,
    #[doc = "< Threshold for free memory in the buffer for each hart."]
    pub threshold: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of trace_config_info_t"][::core::mem::size_of::<trace_config_info_t>() - 12usize];
    ["Alignment of trace_config_info_t"][::core::mem::align_of::<trace_config_info_t>() - 4usize];
    ["Offset of field: trace_config_info_t::event_mask"]
        [::core::mem::offset_of!(trace_config_info_t, event_mask) - 0usize];
    ["Offset of field: trace_config_info_t::filter_mask"]
        [::core::mem::offset_of!(trace_config_info_t, filter_mask) - 4usize];
    ["Offset of field: trace_config_info_t::threshold"]
        [::core::mem::offset_of!(trace_config_info_t, threshold) - 8usize];
};
#[doc = " \\struct trace_buffer_size_header_t\n\\brief Trace buffer header (resides at the beggining of the buffer).\nIt contains size of valid data in that buffer.\nThis header is used for sub-buffers when a buffer is partitioned into sub-bufers."]
#[repr(C, packed)]
#[derive(Debug, Default, Copy, Clone)]
pub struct trace_buffer_size_header_t {
    #[doc = "< Data in the buffer."]
    pub data_size: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of trace_buffer_size_header_t"]
        [::core::mem::size_of::<trace_buffer_size_header_t>() - 4usize];
    ["Alignment of trace_buffer_size_header_t"]
        [::core::mem::align_of::<trace_buffer_size_header_t>() - 1usize];
    ["Offset of field: trace_buffer_size_header_t::data_size"]
        [::core::mem::offset_of!(trace_buffer_size_header_t, data_size) - 0usize];
};
#[doc = " \\struct trace_buffer_std_header_t\n\\brief Trace buffer header (resides at the beggining of the buffer).\nIt contains size of valid data, type of buffer and Esperanto magic\nnumber to validate buffer. It is used for once for the whole buffer\nnot matter if it divided into sub-buffers or not\nNote: This structure must be cache-line aligned, i.e, 64-bytes aligned."]
#[repr(C)]
#[repr(align(64))]
#[derive(Debug, Copy, Clone)]
pub struct trace_buffer_std_header_t {
    #[doc = "< Esperanto magic header."]
    pub magic_header: u32,
    #[doc = "< Trace Layout version Major, Minor, and Patch"]
    pub version: trace_version_t,
    #[doc = "< Buffer type one of enum trace_buffer_type_e."]
    pub type_: u16,
    #[doc = "< Data size after trace buffer standard header. It does not include data\nin sub-buffers (if present)"]
    pub data_size: u32,
    #[doc = "< Size of one partition on Trace buffer, All partitions must be equal in size."]
    pub sub_buffer_size: u32,
    #[doc = "< Number of Trace buffer partitions."]
    pub sub_buffer_count: u16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of trace_buffer_std_header_t"]
        [::core::mem::size_of::<trace_buffer_std_header_t>() - 64usize];
    ["Alignment of trace_buffer_std_header_t"]
        [::core::mem::align_of::<trace_buffer_std_header_t>() - 64usize];
    ["Offset of field: trace_buffer_std_header_t::magic_header"]
        [::core::mem::offset_of!(trace_buffer_std_header_t, magic_header) - 0usize];
    ["Offset of field: trace_buffer_std_header_t::version"]
        [::core::mem::offset_of!(trace_buffer_std_header_t, version) - 4usize];
    ["Offset of field: trace_buffer_std_header_t::type_"]
        [::core::mem::offset_of!(trace_buffer_std_header_t, type_) - 10usize];
    ["Offset of field: trace_buffer_std_header_t::data_size"]
        [::core::mem::offset_of!(trace_buffer_std_header_t, data_size) - 12usize];
    ["Offset of field: trace_buffer_std_header_t::sub_buffer_size"]
        [::core::mem::offset_of!(trace_buffer_std_header_t, sub_buffer_size) - 16usize];
    ["Offset of field: trace_buffer_std_header_t::sub_buffer_count"]
        [::core::mem::offset_of!(trace_buffer_std_header_t, sub_buffer_count) - 20usize];
};
impl Default for trace_buffer_std_header_t {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[doc = " \\struct trace_entry_header_t\n\\brief Information common for different entry types."]
#[repr(C, packed)]
#[derive(Debug, Default, Copy, Clone)]
pub struct trace_entry_header_t {
    #[doc = "< Current cycle"]
    pub cycle: u64,
    #[doc = "< Size of the event payload following the entry header"]
    pub payload_size: u32,
    #[doc = "< (optional) Hart ID of the Hart which is logging Trace"]
    pub hart_id: u16,
    #[doc = "< One of enum trace_type"]
    pub type_: trace_type_e,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of trace_entry_header_t"][::core::mem::size_of::<trace_entry_header_t>() - 16usize];
    ["Alignment of trace_entry_header_t"][::core::mem::align_of::<trace_entry_header_t>() - 1usize];
    ["Offset of field: trace_entry_header_t::cycle"]
        [::core::mem::offset_of!(trace_entry_header_t, cycle) - 0usize];
    ["Offset of field: trace_entry_header_t::payload_size"]
        [::core::mem::offset_of!(trace_entry_header_t, payload_size) - 8usize];
    ["Offset of field: trace_entry_header_t::hart_id"]
        [::core::mem::offset_of!(trace_entry_header_t, hart_id) - 12usize];
    ["Offset of field: trace_entry_header_t::type_"]
        [::core::mem::offset_of!(trace_entry_header_t, type_) - 14usize];
};
#[doc = " \\struct trace_pmc_counters_compute_t\n\\brief A Trace packet strucure for all compute PMC counters."]
#[repr(C, packed)]
#[derive(Debug, Default, Copy, Clone)]
pub struct trace_pmc_counters_compute_t {
    pub header: trace_entry_header_t,
    pub hpmcounter3: u64,
    pub hpmcounter4: u64,
    pub hpmcounter5: u64,
    pub hpmcounter6: u64,
    pub hpmcounter7: u64,
    pub hpmcounter8: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of trace_pmc_counters_compute_t"]
        [::core::mem::size_of::<trace_pmc_counters_compute_t>() - 64usize];
    ["Alignment of trace_pmc_counters_compute_t"]
        [::core::mem::align_of::<trace_pmc_counters_compute_t>() - 1usize];
    ["Offset of field: trace_pmc_counters_compute_t::header"]
        [::core::mem::offset_of!(trace_pmc_counters_compute_t, header) - 0usize];
    ["Offset of field: trace_pmc_counters_compute_t::hpmcounter3"]
        [::core::mem::offset_of!(trace_pmc_counters_compute_t, hpmcounter3) - 16usize];
    ["Offset of field: trace_pmc_counters_compute_t::hpmcounter4"]
        [::core::mem::offset_of!(trace_pmc_counters_compute_t, hpmcounter4) - 24usize];
    ["Offset of field: trace_pmc_counters_compute_t::hpmcounter5"]
        [::core::mem::offset_of!(trace_pmc_counters_compute_t, hpmcounter5) - 32usize];
    ["Offset of field: trace_pmc_counters_compute_t::hpmcounter6"]
        [::core::mem::offset_of!(trace_pmc_counters_compute_t, hpmcounter6) - 40usize];
    ["Offset of field: trace_pmc_counters_compute_t::hpmcounter7"]
        [::core::mem::offset_of!(trace_pmc_counters_compute_t, hpmcounter7) - 48usize];
    ["Offset of field: trace_pmc_counters_compute_t::hpmcounter8"]
        [::core::mem::offset_of!(trace_pmc_counters_compute_t, hpmcounter8) - 56usize];
};
#[doc = " \\struct trace_pmc_counters_sc_t\n\\brief A Trace packet strucure for all shire cache PMC counters."]
#[repr(C, packed)]
#[derive(Debug, Default, Copy, Clone)]
pub struct trace_pmc_counters_sc_t {
    pub header: trace_entry_header_t,
    pub sc_pmc0: u64,
    pub sc_pmc1: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of trace_pmc_counters_sc_t"]
        [::core::mem::size_of::<trace_pmc_counters_sc_t>() - 32usize];
    ["Alignment of trace_pmc_counters_sc_t"]
        [::core::mem::align_of::<trace_pmc_counters_sc_t>() - 1usize];
    ["Offset of field: trace_pmc_counters_sc_t::header"]
        [::core::mem::offset_of!(trace_pmc_counters_sc_t, header) - 0usize];
    ["Offset of field: trace_pmc_counters_sc_t::sc_pmc0"]
        [::core::mem::offset_of!(trace_pmc_counters_sc_t, sc_pmc0) - 16usize];
    ["Offset of field: trace_pmc_counters_sc_t::sc_pmc1"]
        [::core::mem::offset_of!(trace_pmc_counters_sc_t, sc_pmc1) - 24usize];
};
#[doc = " \\struct trace_pmc_counters_ms_t\n\\brief A Trace packet strucure for all mem shire PMC counters."]
#[repr(C, packed)]
#[derive(Debug, Default, Copy, Clone)]
pub struct trace_pmc_counters_ms_t {
    pub header: trace_entry_header_t,
    pub ms_pmc0: u64,
    pub ms_pmc1: u64,
    pub ms_id: u8,
    pub pad: [u8; 7usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of trace_pmc_counters_ms_t"]
        [::core::mem::size_of::<trace_pmc_counters_ms_t>() - 40usize];
    ["Alignment of trace_pmc_counters_ms_t"]
        [::core::mem::align_of::<trace_pmc_counters_ms_t>() - 1usize];
    ["Offset of field: trace_pmc_counters_ms_t::header"]
        [::core::mem::offset_of!(trace_pmc_counters_ms_t, header) - 0usize];
    ["Offset of field: trace_pmc_counters_ms_t::ms_pmc0"]
        [::core::mem::offset_of!(trace_pmc_counters_ms_t, ms_pmc0) - 16usize];
    ["Offset of field: trace_pmc_counters_ms_t::ms_pmc1"]
        [::core::mem::offset_of!(trace_pmc_counters_ms_t, ms_pmc1) - 24usize];
    ["Offset of field: trace_pmc_counters_ms_t::ms_id"]
        [::core::mem::offset_of!(trace_pmc_counters_ms_t, ms_id) - 32usize];
    ["Offset of field: trace_pmc_counters_ms_t::pad"]
        [::core::mem::offset_of!(trace_pmc_counters_ms_t, pad) - 33usize];
};
#[doc = " \\struct trace_pmc_counter_t\n\\brief A Trace packet strucure for a single PMC counter."]
#[repr(C, packed)]
#[derive(Debug, Default, Copy, Clone)]
pub struct trace_pmc_counter_t {
    pub header: trace_entry_header_t,
    pub value: u64,
    pub counter: u8,
    pub pad: [u8; 7usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of trace_pmc_counter_t"][::core::mem::size_of::<trace_pmc_counter_t>() - 32usize];
    ["Alignment of trace_pmc_counter_t"][::core::mem::align_of::<trace_pmc_counter_t>() - 1usize];
    ["Offset of field: trace_pmc_counter_t::header"]
        [::core::mem::offset_of!(trace_pmc_counter_t, header) - 0usize];
    ["Offset of field: trace_pmc_counter_t::value"]
        [::core::mem::offset_of!(trace_pmc_counter_t, value) - 16usize];
    ["Offset of field: trace_pmc_counter_t::counter"]
        [::core::mem::offset_of!(trace_pmc_counter_t, counter) - 24usize];
    ["Offset of field: trace_pmc_counter_t::pad"]
        [::core::mem::offset_of!(trace_pmc_counter_t, pad) - 25usize];
};
#[doc = " \\struct trace_event_cmd_status_t\n\\brief A Trace event strucure for a command execution status."]
#[repr(C, packed)]
#[derive(Copy, Clone)]
pub struct trace_event_cmd_status_t {
    pub __bindgen_anon_1: trace_event_cmd_status_t__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union trace_event_cmd_status_t__bindgen_ty_1 {
    pub __bindgen_anon_1: trace_event_cmd_status_t__bindgen_ty_1__bindgen_ty_1,
    pub raw_cmd: u64,
}
#[repr(C, packed)]
#[derive(Debug, Default, Copy, Clone)]
pub struct trace_event_cmd_status_t__bindgen_ty_1__bindgen_ty_1 {
    #[doc = "< Command message ID"]
    pub mesg_id: u16,
    #[doc = "< Command execution status, One of enum trace_cmd_status"]
    pub cmd_status: trace_cmd_status_e,
    #[doc = "< Submission Queue ID from which command is popped"]
    pub queue_slot_id: u8,
    #[doc = "< transaction ID of command e.g. Tag ID."]
    pub trans_id: u16,
    #[doc = "< Reserved"]
    pub reserved: [u8; 2usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of trace_event_cmd_status_t__bindgen_ty_1__bindgen_ty_1"]
        [::core::mem::size_of::<trace_event_cmd_status_t__bindgen_ty_1__bindgen_ty_1>() - 8usize];
    ["Alignment of trace_event_cmd_status_t__bindgen_ty_1__bindgen_ty_1"]
        [::core::mem::align_of::<trace_event_cmd_status_t__bindgen_ty_1__bindgen_ty_1>() - 1usize];
    ["Offset of field: trace_event_cmd_status_t__bindgen_ty_1__bindgen_ty_1::mesg_id"][::core::mem::offset_of!(
        trace_event_cmd_status_t__bindgen_ty_1__bindgen_ty_1,
        mesg_id
    ) - 0usize];
    ["Offset of field: trace_event_cmd_status_t__bindgen_ty_1__bindgen_ty_1::cmd_status"][::core::mem::offset_of!(
        trace_event_cmd_status_t__bindgen_ty_1__bindgen_ty_1,
        cmd_status
    )
        - 2usize];
    ["Offset of field: trace_event_cmd_status_t__bindgen_ty_1__bindgen_ty_1::queue_slot_id"][::core::mem::offset_of!(
        trace_event_cmd_status_t__bindgen_ty_1__bindgen_ty_1,
        queue_slot_id
    )
        - 3usize];
    ["Offset of field: trace_event_cmd_status_t__bindgen_ty_1__bindgen_ty_1::trans_id"][::core::mem::offset_of!(
        trace_event_cmd_status_t__bindgen_ty_1__bindgen_ty_1,
        trans_id
    ) - 4usize];
    ["Offset of field: trace_event_cmd_status_t__bindgen_ty_1__bindgen_ty_1::reserved"][::core::mem::offset_of!(
        trace_event_cmd_status_t__bindgen_ty_1__bindgen_ty_1,
        reserved
    ) - 6usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of trace_event_cmd_status_t__bindgen_ty_1"]
        [::core::mem::size_of::<trace_event_cmd_status_t__bindgen_ty_1>() - 8usize];
    ["Alignment of trace_event_cmd_status_t__bindgen_ty_1"]
        [::core::mem::align_of::<trace_event_cmd_status_t__bindgen_ty_1>() - 8usize];
    ["Offset of field: trace_event_cmd_status_t__bindgen_ty_1::raw_cmd"]
        [::core::mem::offset_of!(trace_event_cmd_status_t__bindgen_ty_1, raw_cmd) - 0usize];
};
impl Default for trace_event_cmd_status_t__bindgen_ty_1 {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of trace_event_cmd_status_t"]
        [::core::mem::size_of::<trace_event_cmd_status_t>() - 8usize];
    ["Alignment of trace_event_cmd_status_t"]
        [::core::mem::align_of::<trace_event_cmd_status_t>() - 1usize];
};
impl Default for trace_event_cmd_status_t {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[doc = " \\struct trace_entry_header_t\n\\brief A Trace packet strucure for a command execution status."]
#[repr(C, packed)]
#[derive(Copy, Clone)]
pub struct trace_cmd_status_t {
    pub header: trace_entry_header_t,
    pub cmd: trace_event_cmd_status_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of trace_cmd_status_t"][::core::mem::size_of::<trace_cmd_status_t>() - 24usize];
    ["Alignment of trace_cmd_status_t"][::core::mem::align_of::<trace_cmd_status_t>() - 1usize];
    ["Offset of field: trace_cmd_status_t::header"]
        [::core::mem::offset_of!(trace_cmd_status_t, header) - 0usize];
    ["Offset of field: trace_cmd_status_t::cmd"]
        [::core::mem::offset_of!(trace_cmd_status_t, cmd) - 16usize];
};
impl Default for trace_cmd_status_t {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[doc = " \\struct trace_entry_header_t\n\\brief A Trace event strucure for a power status."]
#[repr(C, packed)]
#[derive(Copy, Clone)]
pub struct trace_event_power_status_t {
    pub __bindgen_anon_1: trace_event_power_status_t__bindgen_ty_1,
    pub __bindgen_anon_2: trace_event_power_status_t__bindgen_ty_2,
    pub pad_2: [u8; 4usize],
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union trace_event_power_status_t__bindgen_ty_1 {
    pub __bindgen_anon_1: trace_event_power_status_t__bindgen_ty_1__bindgen_ty_1,
    pub raw_bits_64: u64,
}
#[repr(C, packed)]
#[derive(Debug, Default, Copy, Clone)]
pub struct trace_event_power_status_t__bindgen_ty_1__bindgen_ty_1 {
    #[doc = "< Current Power in mW"]
    pub current_power: u16,
    #[doc = "< Power Throttle State: UP, Down"]
    pub throttle_state: u8,
    #[doc = "< Power State: Max, Managed, Safe, Low"]
    pub power_state: u8,
    #[doc = "< Current Temperature in C"]
    pub current_temp: u8,
    pub pad_1: [u8; 3usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of trace_event_power_status_t__bindgen_ty_1__bindgen_ty_1"]
        [::core::mem::size_of::<trace_event_power_status_t__bindgen_ty_1__bindgen_ty_1>() - 8usize];
    ["Alignment of trace_event_power_status_t__bindgen_ty_1__bindgen_ty_1"][::core::mem::align_of::<
        trace_event_power_status_t__bindgen_ty_1__bindgen_ty_1,
    >() - 1usize];
    ["Offset of field: trace_event_power_status_t__bindgen_ty_1__bindgen_ty_1::current_power"][::core::mem::offset_of!(
        trace_event_power_status_t__bindgen_ty_1__bindgen_ty_1,
        current_power
    )
        - 0usize];
    ["Offset of field: trace_event_power_status_t__bindgen_ty_1__bindgen_ty_1::throttle_state"][::core::mem::offset_of!(
        trace_event_power_status_t__bindgen_ty_1__bindgen_ty_1,
        throttle_state
    )
        - 2usize];
    ["Offset of field: trace_event_power_status_t__bindgen_ty_1__bindgen_ty_1::power_state"][::core::mem::offset_of!(
        trace_event_power_status_t__bindgen_ty_1__bindgen_ty_1,
        power_state
    )
        - 3usize];
    ["Offset of field: trace_event_power_status_t__bindgen_ty_1__bindgen_ty_1::current_temp"][::core::mem::offset_of!(
        trace_event_power_status_t__bindgen_ty_1__bindgen_ty_1,
        current_temp
    )
        - 4usize];
    ["Offset of field: trace_event_power_status_t__bindgen_ty_1__bindgen_ty_1::pad_1"][::core::mem::offset_of!(
        trace_event_power_status_t__bindgen_ty_1__bindgen_ty_1,
        pad_1
    ) - 5usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of trace_event_power_status_t__bindgen_ty_1"]
        [::core::mem::size_of::<trace_event_power_status_t__bindgen_ty_1>() - 8usize];
    ["Alignment of trace_event_power_status_t__bindgen_ty_1"]
        [::core::mem::align_of::<trace_event_power_status_t__bindgen_ty_1>() - 8usize];
    ["Offset of field: trace_event_power_status_t__bindgen_ty_1::raw_bits_64"]
        [::core::mem::offset_of!(trace_event_power_status_t__bindgen_ty_1, raw_bits_64) - 0usize];
};
impl Default for trace_event_power_status_t__bindgen_ty_1 {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union trace_event_power_status_t__bindgen_ty_2 {
    pub __bindgen_anon_1: trace_event_power_status_t__bindgen_ty_2__bindgen_ty_1,
    pub raw_bits_32: u32,
}
#[repr(C, packed)]
#[derive(Debug, Default, Copy, Clone)]
pub struct trace_event_power_status_t__bindgen_ty_2__bindgen_ty_1 {
    #[doc = "< Target Frequency in Mhz"]
    pub tgt_freq: u16,
    #[doc = "< Target Voltage in mV"]
    pub tgt_voltage: u16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of trace_event_power_status_t__bindgen_ty_2__bindgen_ty_1"]
        [::core::mem::size_of::<trace_event_power_status_t__bindgen_ty_2__bindgen_ty_1>() - 4usize];
    ["Alignment of trace_event_power_status_t__bindgen_ty_2__bindgen_ty_1"][::core::mem::align_of::<
        trace_event_power_status_t__bindgen_ty_2__bindgen_ty_1,
    >() - 1usize];
    ["Offset of field: trace_event_power_status_t__bindgen_ty_2__bindgen_ty_1::tgt_freq"][::core::mem::offset_of!(
        trace_event_power_status_t__bindgen_ty_2__bindgen_ty_1,
        tgt_freq
    )
        - 0usize];
    ["Offset of field: trace_event_power_status_t__bindgen_ty_2__bindgen_ty_1::tgt_voltage"][::core::mem::offset_of!(
        trace_event_power_status_t__bindgen_ty_2__bindgen_ty_1,
        tgt_voltage
    )
        - 2usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of trace_event_power_status_t__bindgen_ty_2"]
        [::core::mem::size_of::<trace_event_power_status_t__bindgen_ty_2>() - 4usize];
    ["Alignment of trace_event_power_status_t__bindgen_ty_2"]
        [::core::mem::align_of::<trace_event_power_status_t__bindgen_ty_2>() - 4usize];
    ["Offset of field: trace_event_power_status_t__bindgen_ty_2::raw_bits_32"]
        [::core::mem::offset_of!(trace_event_power_status_t__bindgen_ty_2, raw_bits_32) - 0usize];
};
impl Default for trace_event_power_status_t__bindgen_ty_2 {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of trace_event_power_status_t"]
        [::core::mem::size_of::<trace_event_power_status_t>() - 16usize];
    ["Alignment of trace_event_power_status_t"]
        [::core::mem::align_of::<trace_event_power_status_t>() - 1usize];
    ["Offset of field: trace_event_power_status_t::pad_2"]
        [::core::mem::offset_of!(trace_event_power_status_t, pad_2) - 12usize];
};
impl Default for trace_event_power_status_t {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[doc = " \\struct trace_entry_header_t\n\\brief A Trace packet strucure for a power status."]
#[repr(C, packed)]
#[derive(Copy, Clone)]
pub struct trace_power_status_t {
    pub header: trace_entry_header_t,
    pub power: trace_event_power_status_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of trace_power_status_t"][::core::mem::size_of::<trace_power_status_t>() - 32usize];
    ["Alignment of trace_power_status_t"][::core::mem::align_of::<trace_power_status_t>() - 1usize];
    ["Offset of field: trace_power_status_t::header"]
        [::core::mem::offset_of!(trace_power_status_t, header) - 0usize];
    ["Offset of field: trace_power_status_t::power"]
        [::core::mem::offset_of!(trace_power_status_t, power) - 16usize];
};
impl Default for trace_power_status_t {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[doc = " \\struct trace_entry_header_t\n\\brief A Trace packet strucure for a string message."]
#[repr(C, packed)]
pub struct trace_string_t {
    pub header: trace_entry_header_t,
    pub string: __IncompleteArrayField<::core::ffi::c_char>,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of trace_string_t"][::core::mem::size_of::<trace_string_t>() - 16usize];
    ["Alignment of trace_string_t"][::core::mem::align_of::<trace_string_t>() - 1usize];
    ["Offset of field: trace_string_t::header"]
        [::core::mem::offset_of!(trace_string_t, header) - 0usize];
    ["Offset of field: trace_string_t::string"]
        [::core::mem::offset_of!(trace_string_t, string) - 16usize];
};
impl Default for trace_string_t {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[doc = " \\struct trace_entry_header_t\n\\brief A Trace packet strucure for a memory dump of variable size."]
#[repr(C, packed)]
pub struct trace_memory_t {
    pub header: trace_entry_header_t,
    pub src_addr: u64,
    pub size: u64,
    pub data: __IncompleteArrayField<u8>,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of trace_memory_t"][::core::mem::size_of::<trace_memory_t>() - 32usize];
    ["Alignment of trace_memory_t"][::core::mem::align_of::<trace_memory_t>() - 1usize];
    ["Offset of field: trace_memory_t::header"]
        [::core::mem::offset_of!(trace_memory_t, header) - 0usize];
    ["Offset of field: trace_memory_t::src_addr"]
        [::core::mem::offset_of!(trace_memory_t, src_addr) - 16usize];
    ["Offset of field: trace_memory_t::size"]
        [::core::mem::offset_of!(trace_memory_t, size) - 24usize];
    ["Offset of field: trace_memory_t::data"]
        [::core::mem::offset_of!(trace_memory_t, data) - 32usize];
};
impl Default for trace_memory_t {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[doc = " \\struct dev_context_registers_t\n\\brief A structure containing the device context registers."]
#[repr(C, packed)]
#[derive(Debug, Default, Copy, Clone)]
pub struct dev_context_registers_t {
    pub epc: u64,
    pub tval: u64,
    pub status: u64,
    pub cause: u64,
    pub gpr: [u64; 31usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of dev_context_registers_t"]
        [::core::mem::size_of::<dev_context_registers_t>() - 280usize];
    ["Alignment of dev_context_registers_t"]
        [::core::mem::align_of::<dev_context_registers_t>() - 1usize];
    ["Offset of field: dev_context_registers_t::epc"]
        [::core::mem::offset_of!(dev_context_registers_t, epc) - 0usize];
    ["Offset of field: dev_context_registers_t::tval"]
        [::core::mem::offset_of!(dev_context_registers_t, tval) - 8usize];
    ["Offset of field: dev_context_registers_t::status"]
        [::core::mem::offset_of!(dev_context_registers_t, status) - 16usize];
    ["Offset of field: dev_context_registers_t::cause"]
        [::core::mem::offset_of!(dev_context_registers_t, cause) - 24usize];
    ["Offset of field: dev_context_registers_t::gpr"]
        [::core::mem::offset_of!(dev_context_registers_t, gpr) - 32usize];
};
#[doc = " \\struct trace_execution_stack_t\n\\brief A Trace packet strucure for logging the execution stack of device registers."]
#[repr(C, packed)]
#[derive(Debug, Default, Copy, Clone)]
pub struct trace_execution_stack_t {
    pub header: trace_entry_header_t,
    pub registers: dev_context_registers_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of trace_execution_stack_t"]
        [::core::mem::size_of::<trace_execution_stack_t>() - 296usize];
    ["Alignment of trace_execution_stack_t"]
        [::core::mem::align_of::<trace_execution_stack_t>() - 1usize];
    ["Offset of field: trace_execution_stack_t::header"]
        [::core::mem::offset_of!(trace_execution_stack_t, header) - 0usize];
    ["Offset of field: trace_execution_stack_t::registers"]
        [::core::mem::offset_of!(trace_execution_stack_t, registers) - 16usize];
};
#[doc = " \\struct trace_custom_event_t\n\\brief A Trace packet strucure for logging a custom event in trace buffer."]
#[repr(C, packed)]
pub struct trace_custom_event_t {
    pub header: trace_entry_header_t,
    pub custom_type: u32,
    pub payload_size: u32,
    pub payload: __IncompleteArrayField<u8>,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of trace_custom_event_t"][::core::mem::size_of::<trace_custom_event_t>() - 24usize];
    ["Alignment of trace_custom_event_t"][::core::mem::align_of::<trace_custom_event_t>() - 1usize];
    ["Offset of field: trace_custom_event_t::header"]
        [::core::mem::offset_of!(trace_custom_event_t, header) - 0usize];
    ["Offset of field: trace_custom_event_t::custom_type"]
        [::core::mem::offset_of!(trace_custom_event_t, custom_type) - 16usize];
    ["Offset of field: trace_custom_event_t::payload_size"]
        [::core::mem::offset_of!(trace_custom_event_t, payload_size) - 20usize];
    ["Offset of field: trace_custom_event_t::payload"]
        [::core::mem::offset_of!(trace_custom_event_t, payload) - 24usize];
};
impl Default for trace_custom_event_t {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C, packed)]
#[derive(Debug, Default, Copy, Clone)]
pub struct trace_value_u64_t {
    pub header: trace_entry_header_t,
    pub tag: u32,
    pub value: u64,
    pub pad: [u8; 4usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of trace_value_u64_t"][::core::mem::size_of::<trace_value_u64_t>() - 32usize];
    ["Alignment of trace_value_u64_t"][::core::mem::align_of::<trace_value_u64_t>() - 1usize];
    ["Offset of field: trace_value_u64_t::header"]
        [::core::mem::offset_of!(trace_value_u64_t, header) - 0usize];
    ["Offset of field: trace_value_u64_t::tag"]
        [::core::mem::offset_of!(trace_value_u64_t, tag) - 16usize];
    ["Offset of field: trace_value_u64_t::value"]
        [::core::mem::offset_of!(trace_value_u64_t, value) - 20usize];
    ["Offset of field: trace_value_u64_t::pad"]
        [::core::mem::offset_of!(trace_value_u64_t, pad) - 28usize];
};
#[repr(C, packed)]
pub struct trace_value_u32_t {
    pub header: trace_entry_header_t,
    pub tag: u32,
    pub value: u32,
    pub pad: __IncompleteArrayField<u8>,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of trace_value_u32_t"][::core::mem::size_of::<trace_value_u32_t>() - 24usize];
    ["Alignment of trace_value_u32_t"][::core::mem::align_of::<trace_value_u32_t>() - 1usize];
    ["Offset of field: trace_value_u32_t::header"]
        [::core::mem::offset_of!(trace_value_u32_t, header) - 0usize];
    ["Offset of field: trace_value_u32_t::tag"]
        [::core::mem::offset_of!(trace_value_u32_t, tag) - 16usize];
    ["Offset of field: trace_value_u32_t::value"]
        [::core::mem::offset_of!(trace_value_u32_t, value) - 20usize];
    ["Offset of field: trace_value_u32_t::pad"]
        [::core::mem::offset_of!(trace_value_u32_t, pad) - 24usize];
};
impl Default for trace_value_u32_t {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C, packed)]
#[derive(Debug, Default, Copy, Clone)]
pub struct trace_value_u16_t {
    pub header: trace_entry_header_t,
    pub tag: u32,
    pub value: u16,
    pub pad: [u8; 2usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of trace_value_u16_t"][::core::mem::size_of::<trace_value_u16_t>() - 24usize];
    ["Alignment of trace_value_u16_t"][::core::mem::align_of::<trace_value_u16_t>() - 1usize];
    ["Offset of field: trace_value_u16_t::header"]
        [::core::mem::offset_of!(trace_value_u16_t, header) - 0usize];
    ["Offset of field: trace_value_u16_t::tag"]
        [::core::mem::offset_of!(trace_value_u16_t, tag) - 16usize];
    ["Offset of field: trace_value_u16_t::value"]
        [::core::mem::offset_of!(trace_value_u16_t, value) - 20usize];
    ["Offset of field: trace_value_u16_t::pad"]
        [::core::mem::offset_of!(trace_value_u16_t, pad) - 22usize];
};
#[repr(C, packed)]
#[derive(Debug, Default, Copy, Clone)]
pub struct trace_value_u8_t {
    pub header: trace_entry_header_t,
    pub tag: u32,
    pub value: u8,
    pub pad: [u8; 3usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of trace_value_u8_t"][::core::mem::size_of::<trace_value_u8_t>() - 24usize];
    ["Alignment of trace_value_u8_t"][::core::mem::align_of::<trace_value_u8_t>() - 1usize];
    ["Offset of field: trace_value_u8_t::header"]
        [::core::mem::offset_of!(trace_value_u8_t, header) - 0usize];
    ["Offset of field: trace_value_u8_t::tag"]
        [::core::mem::offset_of!(trace_value_u8_t, tag) - 16usize];
    ["Offset of field: trace_value_u8_t::value"]
        [::core::mem::offset_of!(trace_value_u8_t, value) - 20usize];
    ["Offset of field: trace_value_u8_t::pad"]
        [::core::mem::offset_of!(trace_value_u8_t, pad) - 21usize];
};
#[repr(C, packed)]
pub struct trace_value_float_t {
    pub header: trace_entry_header_t,
    pub tag: u32,
    pub value: f32,
    pub pad: __IncompleteArrayField<u8>,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of trace_value_float_t"][::core::mem::size_of::<trace_value_float_t>() - 24usize];
    ["Alignment of trace_value_float_t"][::core::mem::align_of::<trace_value_float_t>() - 1usize];
    ["Offset of field: trace_value_float_t::header"]
        [::core::mem::offset_of!(trace_value_float_t, header) - 0usize];
    ["Offset of field: trace_value_float_t::tag"]
        [::core::mem::offset_of!(trace_value_float_t, tag) - 16usize];
    ["Offset of field: trace_value_float_t::value"]
        [::core::mem::offset_of!(trace_value_float_t, value) - 20usize];
    ["Offset of field: trace_value_float_t::pad"]
        [::core::mem::offset_of!(trace_value_float_t, pad) - 24usize];
};
impl Default for trace_value_float_t {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[doc = " \\struct trace_user_profile_event_t\n\\brief A Trace pkt structure for profile events."]
#[repr(C, packed)]
#[derive(Debug, Default, Copy, Clone)]
pub struct trace_user_profile_event_t {
    #[doc = "< generic event header"]
    pub header: trace_entry_header_t,
    #[doc = "< ptr to func literal emitting the event"]
    pub func: u64,
    #[doc = "< retiredInsts when the event is emitted"]
    pub retiredInsts: u64,
    #[doc = "< line(4 bytes) region (2 bytes) status (2 bytes)"]
    pub line_region_status: u64,
    #[doc = "< ptr to user region name"]
    pub regionName: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of trace_user_profile_event_t"]
        [::core::mem::size_of::<trace_user_profile_event_t>() - 48usize];
    ["Alignment of trace_user_profile_event_t"]
        [::core::mem::align_of::<trace_user_profile_event_t>() - 1usize];
    ["Offset of field: trace_user_profile_event_t::header"]
        [::core::mem::offset_of!(trace_user_profile_event_t, header) - 0usize];
    ["Offset of field: trace_user_profile_event_t::func"]
        [::core::mem::offset_of!(trace_user_profile_event_t, func) - 16usize];
    ["Offset of field: trace_user_profile_event_t::retiredInsts"]
        [::core::mem::offset_of!(trace_user_profile_event_t, retiredInsts) - 24usize];
    ["Offset of field: trace_user_profile_event_t::line_region_status"]
        [::core::mem::offset_of!(trace_user_profile_event_t, line_region_status) - 32usize];
    ["Offset of field: trace_user_profile_event_t::regionName"]
        [::core::mem::offset_of!(trace_user_profile_event_t, regionName) - 40usize];
};
