//! Raw FFI bindings generated by bindgen at build time.
//!
//! Two independent binding sets are produced (see `build.rs`): [`ops`] covers
//! the character-device uapi (`et_ioctl.h`) together with the device-ops RPC
//! message ABI, and [`trace`] covers the et-trace buffer layout. They are kept
//! in separate modules because the two SDK headers define conflicting
//! `enum trace_buffer_type` tags.
//!
//! Everything here is `unsafe` to use directly; the safe wrappers live in the
//! parent modules.
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(clippy::all)]

/// Driver uapi (`et_ioctl.h`) and device-ops RPC message ABI.
pub mod ops {
    include!(concat!(env!("OUT_DIR"), "/bindings_ops.rs"));
}

/// et-trace buffer layout (`esperanto/et-trace/layout.h`).
pub mod trace {
    include!(concat!(env!("OUT_DIR"), "/bindings_trace.rs"));
}
